name: Manage Blog Publication
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  trigger_rebuild:
    runs-on: ubuntu-latest
    steps:
    - name: Webhook
      uses: distributhor/workflow-webhook@c99fa5ed646f4b2807a92f0ce4993c6826b518e4
      with:
        webhook_url: "${{secrets.WORKFLOW_TARGET}}"
        data: '{ "secret-key": "${{secrets.WORKFLOW_TOKEN}}"}'