name: Manage Blog Publication
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  rebuild_and_rollout:
    runs-on: ubuntu-latest
    steps:
    - name: Webhook
      shell: bash
      run: "curl -X POST -H \"Content-Type: application/json\" ${{ secrets.WORKFLOW_TARGET }} -d '{ \"secret-key\": \"${{ secrets.WORKFLOW_TOKEN }}\"}'"